### ISSUE TITLE
Metadata configuration is far too complex

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#402]
Pull requests  #315 and #396 make metadata fields configurable, but the configuration is far too complex, with its own configuration syntax and a lot of when's and if's. We should probably re-do this configuration to make it easier to understand and make it use a less complex syntax. Additionally, it is also impossible to hide all but a list of certain fields since, right now, all fields have to be explicitly configured, although the list of fields is dynamic.

One idea would be to just specify overrides:

```toml
[metadata.catalog_name]
# show only specific fields, hide all other
show = ['title', 'creator']
# hide specific fields
hide = ['description', 'license']
# mark specific fields as readonly
readonly = ['title', 'subject', 'license']
```
